name: Flutter Tag Windows Build

on:
  workflow_dispatch:

jobs:
  run-flutter-tag-windows-build:
    uses: ./.github/workflows/flutter-build-windows.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}